# Vagrantfile to test Vagrant functionality
Vagrant.configure("2") do |config|
    # Use Ubuntu 22.04 LTS box
    config.vm.box = "ubuntu/jammy64"
  
    # Set VM hostname
    config.vm.hostname = "vagrant-test"
  
    # Provision with a simple shell command
    config.vm.provision "shell", inline: <<-SHELL
      echo "Hello, Kamila!" > /home/vagrant/hello.txt
    SHELL
  end
  