Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.define "wmardinS" do |node|
    node.vm.hostname = "wmardinS"
    node.vm.network "private_network", ip: "192.168.56.110"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end

    node.vm.synced_folder "./confs", "/vagrant/confs"
    node.vm.synced_folder "./scripts", "/vagrant/scripts"

    node.vm.provision "shell", inline: <<-SHELL
      chmod +x /vagrant/scripts/install_k3s.sh
      /vagrant/scripts/install_k3s.sh
    SHELL

  end
end
