Vagrant.configure("2") do |config|
  # Basic variables
  vagrant_box = "generic/debian12"
  provider = "virtualbox"
  server_ip = "192.168.56.110"
  worker_ip = "192.168.56.111"

  # Provisioning scripts
  provision_server = <<-SHELL

    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--bind-address #{server_ip} --flannel-iface eth1 --write-kubeconfig-mode 644" sh -

    while ! systemctl is-active --quiet k3s; do
      echo "Waiting for k3s server to be active..."
      sleep 3
    done
    sudo chmod 777 /var/lib/rancher/k3s/server/node-token
    sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
    echo "Server provisioning done"
  SHELL

  provision_server_worker = <<-SHELL
    while [ ! -f /vagrant/node-token ]; do
      echo "Waiting for token..."
      sleep 2
    done

    curl -sfL https://get.k3s.io | K3S_URL="https://#{server_ip}:6443" K3S_TOKEN="$(cat /vagrant/node-token)" INSTALL_K3S_EXEC="--node-ip #{worker_ip} --flannel-iface eth1" sh -

    while ! systemctl is-active --quiet k3s-agent; do
        echo "Waiting for k3s worker to be active..."
        sleep 3
    done

    echo "Worker provisioning done"
  SHELL

  # VM settings
  nodes = [
    {
      name: "npavelicS",
      IP_address: server_ip,
      CPU: 1,
      RAM: 2048,
      provision: provision_server
    },
    {
      name: "kkwasnySW",
      IP_address: worker_ip,
      CPU: 1,
      RAM: 2048,
      provision: provision_server_worker
    }
  ]

  # Apply settings
  config.vm.box = vagrant_box

  nodes.each do |node|
    config.vm.define node[:name] do |control|
      control.vm.hostname = node[:name]
      control.vm.network "private_network", ip: node[:IP_address]
      control.vm.provider provider do |machine|
        machine.memory = node[:RAM]
        machine.cpus = node[:CPU]
      end
      control.vm.synced_folder ".", "/vagrant"
      control.vm.provision "shell", inline: node[:provision]
    end
  end
end
