
Vagrant.configure("2") do |config|
  vagrant_box = "ubuntu/jammy64"
  provider = "virtualbox"
  provision_server = <<-SHELL
    curl -sfL https://get.k3s.io | sh -
    sleep 10
    cp /var/lib/rancher/k3s/server/node-token /home/vagrant
    echo "WE DID IT GUYS (delete, just for testing, ok?)"
    SHELL
  provision_server_worker = <<-SHELL
    curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(sudo cat home/vagrant/node-token) sh -
    sleep 10
    sudo k3s kubectl get nodes
    echo "WE DID IT AGAIN GUYS (delete, just for testing, ok?)"
    SHELL
  nodes = [
    {
      name: "npavelicS", 
      IP_address: "192.168.56.110", 
      CPU: 1, 
      RAM: 512,
      provision: provision_server
    }, 
    {
      name: "kkwasnySW", 
      IP_address: "192.168.56.111",
      CPU: 1,
      RAM: 512,
      provision: provision_server_worker
    }
  ]

  config.vm.box = vagrant_box

  nodes.each do |node|
    config.vm.define node[:name] do |control|
      control.vm.hostname = node[:name]
      control.vm.network "private_network", ip: node[:IP_address]
      control.vm.provider provider do |machine|
        machine.memory = node[:RAM]
        machine.cpus = node[:CPU]
      end
      control.vm.provision "shell", inline: node[:provision]
    end
  end
end