# This file is used to configure the GitLab Helm chart.
# It is stored alongside the install script as it it not part of
# the other confs.

global:
  externalUrl: http://localhost:8081
  shmism: shmang
  
  hosts:
    domain: localhost
    externalIP: ""
    https: false

  ingress:
    configureCertmanager: false
    class: nginx
    enabled: true
    tls:
      enabled: false

  kas:
    enabled: false

  rails:
    bootsnap:
      enabled: false

nginx-ingress:
  enabled: true

postgresql:
  resources:
    requests:
      memory: 200Mi

prometheus:
  install: false

redis:
  allowEmptyPassword: true
  password: ""
  resources:
    requests:
      memory: 100Mi

registry:
  enabled: false
  hpa:
    maxReplicas: 1
    minReplicas: 1

gitlab:
  gitlab-exporter:
    enabled: false
  gitlab-shell:
    maxReplicas: 1
    minReplicas: 1
  kas:
    maxReplicas: 1
    minReplicas: 1
  sidekiq:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 300M
  toolbox:
    enabled: false
  webservice:
    maxReplicas: 1
    minReplicas: 1
    resources:
      requests:
        memory: 600M
    workerProcesses: 0

gitlab-runner:
  install: false

certmanager:
  install: false
  
certmanager-issuer:
  email: knism@student.42wolfsburg.de
